### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by xerotolerant** [doebi/liquidfun.js#1]
Hello. I am attempting to build your version using emscripten on ubuntu.

I am getting the error:

python /usr/share/emscripten/tools/webidl_binder.py liquidfun.idl liquidfun_glue
Traceback (most recent call last):
  File "/usr/share/emscripten/tools/webidl_binder.py", line 15, in <module>
    import WebIDL
ImportError: No module named WebIDL
Makefile:87: recipe for target 'liquidfun_glue.cpp' failed
make: **\* [liquidfun_glue.cpp] Error 1

To be honest I an not really sure that this message is the fault of the author. I've been unable to build any version of liquidfun on any OS and I am out of options.

**Comment by doebi** [comment]
looks like your emscripten installation is corrupt.

The tool, which fails is: https://github.com/kripken/emscripten/blob/master/tools/webidl_binder.py

On line 12, 13 you can see it adding some directories to the python PATH, before importing "WebIDL" on line 15. Which it can't find.

So yeah, this issue is not directly associated with this repo. Solving this would need deeper inspection of your system and especially your environment variables.

Hope this helps. Cheers.

**Comment by doebi** [comment]
To bypass the struggle of compiling you can also use my precompiled version for now.
http://files.doebi.at/lfjs

**Comment by xerotolerant** [comment]
Hello. Thanks for compiling it. I am trying to use it and I noticed that
you said that there are usage differences. What are they?
Simply replacing the liquidfun.js file from google doesn't work. I am
trying to rebuild my simulation from scratch but I don't really know where
to start with your library.

**Comment by doebi** [comment]
The usage is pretty much the same as box2d.js.
https://github.com/kripken/box2d.js#usage-webidl-bindings

Basically it's just omitting the usage of "Box2D." in front of class names and using setter/getter methods for attributes instead of accessing them directly.

**Comment by xerotolerant** [comment]
Oh Ok. Thanks I was tinkering with it and I realized. Thanks a lot sir. I
am looking forward to using some of the functionality that is not available
in the official port like collision detection and automatic particle
destruction.
I wish I was as advanced as you guys are to be able to compile it myself
but this is some complicated stuff.

On Mon, Feb 15, 2016 at 10:27 AM, Christoph Döberl <notifications@github.com

**Comment by xerotolerant** [comment]
Hey man sorry to bother you so much.
I am following the usage instructions you sent from
https://github.com/kripken/box2d.js#usage-webidl-bindings

I don't know if this is a bug or not or how to tell even but

_blockBodyDef.set_type(b2_dynamicBody);_

yields the error "Uncaught ReferenceError: b2_dynamicBody is not defined"

Is there a tutorial for your version somewhere?

**Comment by doebi** [comment]
Yeah right. "Box2D.b2_dynaimcBody" might work.
or just use 2.
