### ISSUE TITLE
http://files.doebi.at/lfjs is down

### ISSUE THREAD

**Issue by dadaphl** [doebi/liquidfun.js#2]
Hello,

i wanted to download your build, but the server seems to be down. I'd be great if you could publish the final build somewhere. I cant seem to get the build processes working on my machine.

Cheers

**Comment by doebi** [comment]
You're right, I am sorry for that.

Here you are: [liquidfun.tar.gz](https://github.com/doebi/liquidfun.js/files/631945/liquidfun.tar.gz)

Have fun!
